# Generated by Django 4.2.6 on 2023-10-26 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='canie_estrutura_hidrografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.TextField(blank=True, null=True)),
                ('c2', models.TextField(blank=True, null=True)),
                ('c3', models.TextField(blank=True, null=True)),
                ('c4', models.TextField(blank=True, null=True)),
                ('c5', models.TextField(blank=True, null=True)),
                ('c6', models.TextField(blank=True, null=True)),
                ('c7', models.TextField(blank=True, null=True)),
                ('c8', models.TextField(blank=True, null=True)),
                ('c9', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='historico_canie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.TextField(blank=True, null=True)),
                ('c2', models.TextField(blank=True, null=True)),
                ('c3', models.TextField(blank=True, null=True)),
                ('c4', models.TextField(blank=True, null=True)),
                ('c5', models.TextField(blank=True, null=True)),
                ('c6', models.TextField(blank=True, null=True)),
                ('c7', models.TextField(blank=True, null=True)),
                ('c8', models.TextField(blank=True, null=True)),
                ('c9', models.TextField(blank=True, null=True)),
                ('c10', models.TextField(blank=True, null=True)),
                ('c11', models.TextField(blank=True, null=True)),
                ('c12', models.TextField(blank=True, null=True)),
                ('c13', models.TextField(blank=True, null=True)),
                ('c14', models.TextField(blank=True, null=True)),
                ('c15', models.TextField(blank=True, null=True)),
                ('c16', models.TextField(blank=True, null=True)),
                ('c17', models.TextField(blank=True, null=True)),
                ('c18', models.TextField(blank=True, null=True)),
                ('c19', models.TextField(blank=True, null=True)),
                ('canie_json', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=255, verbose_name='NOME COMPLETO')),
                ('cpf', models.CharField(help_text='000.000.000-00', max_length=255, verbose_name='CPF')),
                ('fone', models.CharField(help_text='Dê preferência ao número do Whatsapp', max_length=15, verbose_name='TELEFONE')),
                ('doc_inserido', models.BooleanField(default=False)),
                ('contrato_enviado', models.BooleanField(default=False, verbose_name='CONTRATO ENVIADO')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('documento', models.FileField(max_length=2000, upload_to='documento_contrato', verbose_name='Documento')),
                ('doc_base64_txt', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cliente_documentos', to='cliente.pessoa')),
            ],
            options={
                'ordering': ['cliente'],
            },
        ),
    ]
